---
title: "Exploring Quarto and Latex"
author: "Edlyn Bel D. De Guzman"
format: pdf
editor: visual
---

### ***4.1 ANTIDIFFERENTIATION AND INDEFINITE INTEGRALS***

### 4.1.2 Integration by Substitution

::: {#thm-line}
## **Substitution rule**

If $u = g(x)$ is a differentiable function whose range is an interval $I$ and $f$ is continuous on $I$, then

$$
\int f(g(x))\cdot g'(x)\,dx = \int f(u)\,du
$$
:::

::: {#exm-line}
1.  $\displaystyle\int (1-4x)^{1/2}\,dx$

    If we let $u=1-4x$, then $du=-4\,dx$. We multiply the integrand by $\frac{-4}{-4}$. Thus, 
$$\int (1-4x)^{1/2}\,dx = \int (1-4x)^{1/2}\;\cdot\;\frac{-4}{-4}\;dx = \int u^{1/2}\left(-\dfrac{du}{4}\right)\;dx =-\frac{1}{4} \int u^{1/2}\;du = -\frac{1}{4}\;\cdot\;\frac {2u^{3/2}}{3}\;+\;C.$$ 
We put the final answer in terms $x$ by substituting $u=1-4x$. Therefore, 
$$ \int (1-4x)^{1/2} \; dx= \frac {(1-4x)^{3/2}}{6}\;+\;C.$$

2.  $\displaystyle\int x^2(x^{3}-1)^{10} \, dx$

    Let $u=x^3-1$. Then $du=3x^2\,dx$, or $\frac{du}{3}=x^2\,dx$. By substitution, $$\int x^2(x^{3}-1)^{10} \, dx=\int u^{10}\cdot\frac{du}{3}=\frac{1}{3}\int u^{10}\,du = \frac {u^{11}}{33}+\,C=\frac {(x^3-1)^{11}}{33}\;+\;C.$$

3.  $\displaystyle\int \frac{x}{(x^2+1)^3}\;dx$

    Let $u=x^2+1$. Then $du=2x\;dx$, or $\frac{du}{2}=x\;dx$. By substitution, $$\int\frac{x}{(x^2+1)^3}\;dx=\frac{1}{2}\int u^{-3}\;du=\frac{1}{2}\,\cdot\,\frac{u^{-2}}{-2}+\,C=-\frac{1}{4(x^2+1)^2}\;+\;C.$$

4.  $\displaystyle\int \cos^4x\;\sin x\;dx$

    Let $u=\cos x$. Then $du=-\sin x\;dx$, or $-du=\sin x\;dx$. By substitution, $$\int \cos^4 x\;\sin x\;dx=-\int u^4\;du=-\frac{u{^5}}{5}+\,C=-\frac{\cos{^5}x}{5}\;+\;C.$$

5.  $\displaystyle\int x\;\sec^3\;(x^2)\;\tan\;(x^2)\;dx$

    Let $u=\sec\;(x^2)$.Then $du=\sec\;(x^2)\;\tan\;(x^2)\;\cdot\;2x\;dx$, or $\frac{du}{2}=\sec\;(x^2)\;\tan\;(x^2)\;\cdot\;x\;dx$. By substitution, $$\begin{aligned}
    \int x\;\sec^3\;(x^2)\;\tan\;(x^2)\;dx &= \int \sec^2\;(x^2)\;\sec\;(x^2)\;\tan\;(x^2)\;\cdot\;x\;dx\\ &=\frac {1}{2}\int u^2\;du=\frac {1}{2}\;\cdot\;\frac{u^3}{3}\;+\;C\\ &= \frac {\sec^3\;(x^2)}{6}\;+\;C.\end{aligned}$$

6.  $\displaystyle\int \frac {{\tan\;\frac{1}{s}\;+\;\tan\;\frac {1}{s}\;\sin\;\frac {1}{s}}} {s^2\;\cos\;\frac{1}{s}}\;ds$

    Let $u=\frac{1}{s}$. Then $du=-\frac{1}{s^2}\;ds$ or $-du=\frac{ds}{s^2}$. By substitution, $$\begin{aligned}\int\frac {{\tan\;\frac{1}{s}\;+\;\tan\;\frac {1}{s}\;\sin\;\frac {1}{s}}} {s^2\;\cos\;\frac{1}{s}}\;ds &= -\int\frac{tan\;u\;+\;\tan\;u\;\sin\;u}{\cos\;u}\;du\\ &=-\int(\sec\;u\;\tan\;u\;+\;\tan^2\;u)\;du\\ &= -\int(\sec\;u\;\tan\;u\;+\;\sec^2\;u\;-\;1)\;du\\ &=-\;(\sec\;u\;+\;\tan\;u\;-\;u)\;+\;C\\ &= -\;\sec\;\frac{1}{s}\;-\;\tan\;\frac{1}{s}\;+\;\frac {1}{s}\;+\;C.\end{aligned}$$

7.  $\displaystyle\int t\sqrt{t-1}\;dt$

    Let $u=t-1$. Then $u=dt$. Also, $t=u+1$. By substitution, $$\begin{aligned}\int t\sqrt{t-1}\;dt &=\int(u+1)\;u^{1/2}\;du=\int(u^{3/2}\;+\;u^{1/2})\;du=\frac{2u^{5/2}}{5}\;+\;\frac{2u^{3/2}}{3}\;+\;C\\ &=\frac{2(t-1)^{5/2}}{5}\;+\;\frac{2(t-1)^{3/2}}{3}\;+\;C.\end{aligned}$$

8.  $\displaystyle\int\frac{t^3}{\sqrt{t^2+3}}\;dt$

    Let $u=t^2+3$. Then $du=2t\;dt$, or $\frac{du}{2}=t\;dt$. Also, $t^2=u-3$. By substitution, $$\begin{aligned}\int\frac{t^3}{\sqrt{t^2+3}}\;dt &=\int\frac{t^2\;\cdot\;t}{\sqrt{t^2+3}}\;dt=\int u^{-1/2}\;(u-3)\;\frac{du}{2}\\ &=\frac {1}{2}\int(u^{1/2}-3u^{-1/2})\;du=\frac{1}{2}\left(\dfrac{2u^{3/2}}{3}-6u^{1/2}\right)\;+\;C\\ &=\frac{(t^2+3)^{3/2}}{3}-3(t^2+3)^{1/2}\;+\;C.\end{aligned}$$

9.  $\displaystyle\int\sqrt{4+\sqrt{x}}\;dx$

    Let $u=4+\sqrt{x}$. Then $du=\frac{1}{2\sqrt{x}}\;dx$ or $2\;du=\frac{dx}{\sqrt{x}}$. By substitution, $$\begin{aligned}\int\sqrt{4+\sqrt{x}}\;dx &=\int\sqrt{4+\sqrt{x}}\;\cdot\;\frac{\sqrt{x}}{\sqrt{x}}\;dx\\ &=\int\sqrt{4+\sqrt{x}}\;\cdot\;\sqrt{x}\;\cdot\;\frac{dx}{\sqrt{x}}\;\;\;\;\;\;(\sqrt{x}=u-4)\\ &=\int u^{1/2}\;\cdot\;(u-4)\;\cdot\;2\;du\\ &=\int(2u^{3/2}-8u^{1/2})\;du\\ &=\frac{2\;\cdot\;2u^{5/2}}{5}-\frac{2\;\cdot\;8u^{3/2}}{3}\;+\;C\\ &=\frac{4(4+\sqrt{x})^{5/2}}{5}-\frac{16(4+\sqrt{x})^{3/2}}{3}\;+\;C.\end{aligned}$$
:::

# **5.6 Indeterminate Forms and L'Hôpital's Rule**

## **5.6.1 Indeterminate Forms of Type** $\frac{0}{0}$ and $\frac{\infty}{\infty}$

We began this course with the concept of the limit: the behavior of a function as the independent variable approaches a certain value, or as it increases or decreases without bound. We saw tangent lines, rates of change, and areas of a plane regions, as limits of certain quantities. Indeed, the concept of the limit is the central idea about which the entire calculus revolves.

Now, we conclude this course by revisiting the fundamental idea. We shall see that, with the aid of derivatives, certain limits can be evaluated more conveniently. Before proceeding, we first recall some terminology defined in the early part of this course. We also recall here some techniques in evaluating limits we have previously encountered.

::: {#def-line}
The $\displaystyle\lim_{x \to a} \frac{f(x)}{g(x)}$ is an indeterminate form of type

1.  $\frac{0}{0}$ if $\displaystyle\lim_{x \to a} f(x)=\lim_{x\to a}g(x)=0.$

2.  $\frac{\infty}{\infty}$ if $\displaystyle\lim_{x\to a}f(x)$ and $\displaystyle\lim_{x\to a}g(x)$ are both $+\infty$ or $-\infty$.
:::

Of course, $“x \to a”$ may be replaced by $“x \to a^+”$, $“x \to a^-”$, $“x \to +\infty”$ or$“x \to -\infty”.$

:::{#exm-line}
Evaluate the following limits.

1.  $\displaystyle\lim_{x\to 0}\frac {x^2-3x}{2x^2+x}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)$

    **Solution.**

    $\;\;\;\;\;\;\displaystyle\lim_{x \to 0}\frac{x^2-3x}{2x^2+x}=\lim_{x \to 0}\frac{x(x-3)}{x(2x+1)}=\lim_{x \to 0}\frac{x-3}{2x+1}=-3$

2.  $\displaystyle\lim_{x\to 0}\frac{\sin\;5x}{\sin\;3x}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)$

    **Solution.**

    $\;\;\;\;\;\;\displaystyle\lim_{x\to 0}\frac{\sin\;5x}{\sin\;3x}=\lim_{x \to 0}\left(\dfrac{\sin\;5x}{5x} \right)\left(\dfrac{3x}{\sin\;3x}\right)\left(\dfrac{5}{3}\right)=1\;\cdot\;1\;\cdot\;\frac{5}{3}=\frac{5}{3}$

3.  $\displaystyle\lim_{x\to 2^-}\frac{x^2+3x-10}{x^2-4x+4}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)$

    **Solution.**

    $\;\;\;\;\;\;\begin{aligned}\displaystyle\lim_{x\to 2^-}\frac{x^2+3x-10}{x^2-4x+4} &=\lim_{x\to 2^-}\frac{(x+5)(x-2)}{(x-2)^2}\\ &=\lim_{x \to 2^-}\frac{(x+5)}{x-2}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{7}{0^-}\right)\\ &=-\infty\end{aligned}$

4.  $\displaystyle\lim_{x\to +\infty}\frac{3x-1}{7-6x}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{+\infty}{-\infty}\right)$

    **Solution.**

    $\;\;\;\;\;\;\displaystyle\lim_{x\to +\infty}\frac{3x-1}{7-6x}=\lim_{x\to+\infty}\frac{3x-1}{7-6x}\;\cdot\;\frac{\frac{1}{x}}{\frac{1}{x}}=\lim_{x\to+\infty}\frac{3-\frac{1}{x}}{\frac{7}{x}-6}=-\frac{1}{2}$
:::

## **5.6.2 L'Hôpital's Rule**

The following theorem tells us how derivatives can be evaluate limits that are indeterminate of type $\frac{0}{0}$ or $\frac{\infty}{\infty}$. It is usually referred to as *L'Hôpital's Rule*, afer the French mathematician Guillaume François Marquis De L'Hôpital.

:::{#thm-line}

Let $f$ and $g$ be functions differentiable on an open interval $I$ containing $a$ except possibly at $a$ and $g'(x)\neq 0$ for all $x\in I \setminus \{a\}$.If $\displaystyle\lim_{x\to a}\frac{f(x)}{g(x)}$ is indeterminate of type $\frac{0}{0}$ or $\frac{\infty}{\infty}$, then

$$\displaystyle\lim_{x\to a}\frac{f(x)}{g(x)}=\lim_{x\to a}\frac{f'(x)}{g'(x)}$$
provided $\displaystyle\lim_{x \to a}\frac{f'(x)}{g'(x)}$ exists or $\displaystyle\lim_{x \to a}\frac{f'(x)}{g'(x)}=\pm\infty$
:::

**Remark 5.6.4**. L'Hôpital's Rule, with suitable modifications, is valid if $“x \to a”$ is replaced by $“x \to a^+”$, $“x \to a^-”$, $“x \to +\infty”$ or $“x \to -\infty”$.

:::{#exm-line}

Evaluate the following limits.

1.  $\displaystyle\lim_{x\to 0}\frac{x^2-3x}{2x^2+x}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)$

    **Solution.**

    $\;\;\;\;\;\;\displaystyle\lim_{x\to 0}\frac{x^2-3x}{2x^2+x}=\lim_{x\to 0}\frac{Dx(x^2-3x)}{Dx(2x^2+x)}=\lim_{x\to0}\frac{2x-3}{4x+1}=-3$

2.  $\displaystyle\lim_{x\to 0}\frac{\sin 5x}{\sin 3x}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)$

    **Solution.**

    $\;\;\;\;\;\;\displaystyle\lim_{x\to0}\frac{\sin 5x}{\sin 3x}=\lim_{x\to0}\frac{5\cos5x}{3\cos3x}=\frac{5}{3}$

3.  $\displaystyle\lim_{x\to2^-}\frac{x^2+3x-10}{x^2-4x+4}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)$

    **Solution.**

    $\;\;\;\;\;\;\begin{aligned}\displaystyle\lim_{x\to2^-}\frac{x^2+3x-10}{x^2-4x+4}&=\lim_{x\to2^-}\frac{2x+3}{2x-4}\;\;\;\;\;\;\;\;\;\;\;\left(\dfrac{7}{0^-}\right)\\ &=-\infty\end{aligned}$

4.  $\displaystyle\lim_{x\to+\infty}\frac{3x-1}{7-6x}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{+\infty}{-\infty}\right)$

    **Solution.**

    $\;\;\;\;\;\;\displaystyle\lim_{x\to+\infty}\frac{3x-1}{7-6x}=\lim_{x\to +\infty}\frac{3}{-6}=-\frac{1}{2}$

5.  $\displaystyle\lim_{x\to1}\frac{x^3-3x+2}{1-x+\ln x}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)$

    **Solution.**

    $\;\;\;\;\;\;\begin{aligned}\displaystyle\lim_{x\to1}\frac{x^3-3x+2}{1-x+\ln x} &=\lim_{x\to1}\frac{3x^2-3}{-1+\frac{1}{x}}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)\\ &=\lim_{x\to1}\frac{6x}{-\frac{1}{x^2}}\\ &=-6\end{aligned}$

6.  $\displaystyle\lim_{x\to0^-}\frac{\csc x}{1-\cot x}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{-\infty}{+\infty}\right)$

    **Solution.**

    $\begin{aligned}\;\;\;\;\;\;\displaystyle\lim_{x\to0^-}\frac{\csc x}{1-\cot x} &=\lim_{x\to 0^-}\frac{-\csc x\cot x}{\csc^2x}\\ &=\lim_{x\to0^-}\frac{-\cot x}{\csc x}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{+\infty}{-\infty}\right)\\ &=\lim_{x\to0^-}\frac{\csc^2x}{-\csc x\cot x}\\ &= \lim_{x\to0^-}\frac{\csc x}{-\cot x}\;\;\;\;\;\;\;\;\;\;\left(\dfrac{-\infty}{+\infty}\right)\\ &= \lim_{x\to 0^-}\frac{-\cot x}{\csc x}\end{aligned}$
:::

Observe that the expression in the last line above is exactly the same as the expression in the seconde line. Hence, continued application of L'Hôpital's Rule here will just lead us to an infinite string of equations and will not help us evaluate the limit. This example should make you realize that L'Hôpital's Rule is not always helpful. Sometimes, we just have to use some old-fashioned tricks. For instance, we evaluate the limit by simply manipulating the given expression to obtain a simpler expression.

$$\lim_{x\to 0^-}\frac{\csc x}{1-\cot x}=\lim_{x\to0^-}\frac{\frac{1}{\sin x}}{1-\frac{\cos x}{\sin x}}$$ $\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;\;=\displaystyle\lim_{x\to0^-}\frac{1}{\sin x-\cos x}=-1$

It is imperative to remember the behavior of each function introduced in this course; doing so will help us in computing new limits. Recalling the graphs of our new functions will be helpful in remembering their behavior. For instance, using the graph of $f(x)=\log_a x$, where $0<a<1$ , one sees that $\displaystyle\lim_{x\to0^+}\log_ax=+\infty$. Thus, if $f(x)$ approaches $0$ through positive values as $x$ approaches $k$, then

$$\lim_{x\to k}\log_a[f(x)]=\lim_{y \to 0^+}\log_ay=+\infty$$

:::{#exm-line}
Evaluate: $\displaystyle\lim_{x\to +\infty}\frac{x+\sin x}{x}$

**Solution.**

Note that since $x+\sin x\ge x-1$ for any $x\in \mathbb{R}$ and $\displaystyle\lim_{x\to +\infty}x-1=+\infty$, then $\displaystyle\lim_{x \to +\infty}x+\sin x=+\infty$ as well. Thus, the limit is indeterminate of type $\left(\dfrac{\infty}{\infty}\right).$

However, $\displaystyle\lim_{x\to+\infty}\frac{Dx(x+\sin x)}{Dx(x)}=\lim_{x\to +\infty}\frac{1+\cos x}{1}$ does not exist since $\cos x$ does not approach any particular value as $x\to+\infty$. Neither does $1+\cos x$ grow without bound. Thus, L'Hôpital's Rule does not apply.

We therefore need to employ other techniques. In particular, notice that for any $x> 0$, the following hold:
$$\begin{aligned}
x-1 &\le x+\sin x \; \le x+1 \\ 
\iff \frac{x-1}{x} &\le \frac{x+\sin x}{x} \le \frac{x+1}{x}
\end{aligned}
$$ Also, $\displaystyle\lim_{x\to +\infty}\frac{x-1}{x}=1=\lim_{x\to+\infty}\frac{x+1}{x}$, so by the Squeeze Theorem, $\displaystyle\lim_{x\to +\infty}\frac{x+\sin x}{x}=1$
:::

### 5.6.3 Indeterminate Forms of Type $0\cdot\infty$ and $\infty-\infty$

::: {#def-line}
1.  The $\displaystyle\lim_{x \to a}f(x)g(x)$ is an indeterminate form of type $0\cdot \infty$ and $\infty-\infty$

\center $\displaystyle\lim_{x\to a}f(x)=0$ and $\displaystyle\lim_{x\to a}g(x)=+\infty$ or $-\infty$, or
\center $\displaystyle\lim_{x\to a}f(x)=+\infty$ or $-\infty$ and $\displaystyle\lim_{x \to a}g(x)=0.$

2. The $\displaystyle\lim_{x \to a}f(x)+g(x)$ is an indeterminate form of type $\infty-\infty$ if either

\center $\displaystyle\lim_{x \to a}f(x)=+\infty$ and $\displaystyle\lim_{x \to a}g(x)=-\infty$, or
\center $\displaystyle\lim_{x\to a}f(x)=-\infty$ and $\displaystyle\lim_{x\to a}g(x)=+\infty.$
:::

**Remark 5.6.8.** L'Hôpital's Rule works only for indeterminate forms of type $\frac{0}{0}$ and $\frac{\infty}{\infty}$. Any other indeterminate form must be expressed equivalently in one of these two forms if we wish to apply L'Hôpital's Rule. For the new indeterminate forms described above, these conversions can be performed as described below. 

1. If $\displaystyle\lim_{x\to a}f(x)=0$ and $\displaystyle\lim_{x\to a}g(x)=+\infty$ or $-\infty$, write $\displaystyle\lim_{x\to a}f(x)g(x)$ as:
   
   (a). $\displaystyle\lim_{x\to a}\frac{f(x)}{g(x)}$, which is indeterminate of type $\frac{0}{0}$, or
   
   (b). $\displaystyle\lim_{x \to a}\frac{g(x)}{\frac{1}{f(x)}}$, which is indeterminate of type $\frac{\infty}{\infty}$
   
   and apply L'Hôpital's Rule.
   
2. If $\displaystyle\lim_{x \to a}f(x)+g(x)$ is indeterminate of type $\infty-\infty$, rewrite $f(x)+g(x)$ as a singe expression to obtain an indeterminate form of type $\frac{0}{0}$ or $\frac{\infty}{\infty}$ and apply L'Hôpital's Rule.

:::{#exm-line}
Evaluate the following limits.

1. $\displaystyle\lim_{x\to 0^+}\sin^{-1}(2x)\csc x \;\;\;\;\;\;\;\;\;\;(0\cdot+\infty)$

   **Solution.**
$$\begin{aligned}
\displaystyle\lim_{x\to 0^+}\sin^{-1}(2x)\csc x 
&=\lim_{x\to 0^+}\frac{\sin^{-1}(2x)}{\sin x} \;\;\;\;\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)\\
&=\lim_{x\to 0^+}\frac{\frac{1}{\sqrt{1-4x^2}}\cdot(2)}{\cos x}\\
&= \frac{2}{1}\\ &=2
\end{aligned}$$

2. $\displaystyle\lim_{\theta \to \frac{\pi}{2}^-}\tan\theta\ln(\sin\theta)\;\;\;\;\;\;\;\;\;\;(+\infty\cdot 0)$

   **Solution.**
$$
\begin{aligned}
\displaystyle\lim_{\theta \to \frac{\pi}{2}^-}\tan\theta\ln(\sin\theta)
&=\lim_{\theta \to \frac{\pi}{2}^-}\frac{\ln(\sin \theta)}{\cot \theta}\;\;\;\;\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right) \\ 
&=\lim_{\theta \to \frac{\pi}{2}^-}\frac{\left(\dfrac{1}{\sin \theta}\right)\cos \theta}{\csc^2\theta}\\
&=\lim_{\theta \to \frac{\pi}{2}^-}-\sin\theta \cos\theta\\
&=-1(0)\\
&=0
\end{aligned}
$$

3. $\displaystyle\lim_{x \to 1^+}\left(\dfrac{x}{x-1}-\frac{1}{\ln x}\right)\;\;\;\;\;\;\;\;\;\;\;\;\;\;\left(\dfrac{1}{0^+}-\frac{1}{0^+}\right)$

   **Solution.**
$$\begin{aligned}\displaystyle\lim_{x \to 1^+}\left(\dfrac{x}{x-1}-\frac{1}{\ln x}\right)
&=\lim_{x\to 1^+}\frac{x\ln x-(x-1)}{(x-1)\ln x}\;\;\;\;\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)\\
&=\lim_{x \to 1^+}\frac{x\;\cdot\;\frac{1}{x}+\ln x-1}{(x-1)\;\cdot\;\frac{1}{x}+\ln x}\\
&=\lim_{x\to 1^+}\frac{\ln x}{1-\frac{1}{x}+\ln x}\;\;\;\;\;\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)\\
&=\lim_{x \to 1^+}\frac{\frac{1}{x}}{\frac{1}{x^2}+\frac{1}{x}}\\
&=\frac{1}{2}
\end{aligned}$$
:::

### 5.6.4 Indeterminate Forms of Type $1^{\infty}$, $0^0$ and $\infty^0$

:::{#def-line}
Let $f$ be a nonconstant function. the $\displaystyle\lim_{x \to a}f(x)^{g(x)}$ is an indeterminate form of type

1. $1^\infty$ if $\displaystyle\lim_{x \to a}f(x)=1$ and $\displaystyle\lim_{x\to a}g(x)=+\infty$ or $-\infty.$

2. $0^0$ if $\displaystyle\lim_{x\to a}f(x)=0$, through positive values, and $\displaystyle\lim_{x\to a}g(x)=0.$

3. $\infty^0$ if $\displaystyle\lim_{x\to a}f(x)=+\infty$ and $\displaystyle\lim_{x\to a}g(x)=0.$
:::

**Remark 5.6.11.** If $\displaystyle\lim_{x\to a}f(x)^{g(x)}$ is indeterminate of type $1^\infty$, $0^0$ or $\infty^0$, we write 

$$\displaystyle\lim_{x\to a}f(x)^{g(x)}=\lim_{x\to a}e^{g(x)\ln[f(x)]}$$

and evaluate $\displaystyle\lim_{x\to a}g(x)\ln[f(x)]$ first. Then, if

1. $\displaystyle\lim_{x \to a}g(x)\ln[f(x)]=L\in \mathbb R$, then $\displaystyle\lim_{x \to a}f(x)^{g(x)}=e^L.$

2. $\displaystyle\lim_{x\to a}g(x)\ln[f(x)]=+\infty$, then $\displaystyle\lim_{x\to a}f(x)^{g(x)}=+\infty$.

3. $\displaystyle\lim_{x\to a}g(x)\ln[f(x)]=-\infty$, then $\displaystyle\lim_{x\to a}f(x)^{g(x)}=0.$

:::{#exm-line}
Evaluate the following limits.

1. $\displaystyle\lim_{x\to 0^+}x^{\sin x}\;\;\;\;\;\;\;\;\;(0^0)$

   **Solution.**
   
   First, write $x^{\sin x}=e^{\sin x \ln x}$. Evaluate first $\displaystyle\lim_{x\to 0^+}\sin x \ln x$.

$$\begin{aligned}&\displaystyle\lim_{x\to 0^+}\sin x \ln x\;\;\;\;\;\;\;\;\;(0\;\cdot\;(-\infty))\\
&= \lim_{x\to 0^+}\frac{\ln x}{\csc x}\;\;\;\;\;\;\;\;\;\left(\dfrac{-\infty}{+\infty}\right)\\
&= \lim_{x \to 0^+}\frac{\frac{1}{x}}{-\csc x \cot x}\\
&= \lim_{x\to 0^+}\frac{-\sin^2 x}{x \cos x}\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)\\
&= \lim_{x\to 0^+}\frac{-2\sin x \cos x}{x(-\sin x)+\cos x}\\
&= 0.
\end{aligned}$$
   
   Hence, $\displaystyle\lim_{x \to 0^+}x^{\sin x}=e^0=1$

2. $\displaystyle\lim_{x \to +\infty}\left(1-\dfrac{3}{x}\right)^{2x}\;\;\;\;\;\;\;\;\;(1^\infty)$
   
   **Solution.**
   
   $\left(1-\dfrac{3}{x}\right)^{2x}=e^{2x\ln\left(1-\dfrac{3}{x}\right)}$
   
$$
\begin{aligned}
&\displaystyle\lim_{x\to +\infty}2x \ln\left(1-\dfrac{3}{x}\right)\;\;\;\;\;\;\;\;\;(+\infty\;\cdot\;0)\\
&= \lim_{x\to +\infty}\frac{\ln\left(1-\dfrac{3}{x}\right)}{\frac{1}{2x}}\;\;\;\;\;\;\;\;\;\left(\dfrac{0}{0}\right)\\
&= \lim_{x\to +\infty}\frac{\frac{1}{1-\frac{3}{x}}\;\cdot\;\left(\dfrac{3}{x^2}\right)}{-\frac{1}{2x^2}}\\
&= \lim_{x\to +\infty}\frac{-6}{1-\frac{3}{x}}\\
&= -6
\end{aligned}$$

  Hence, $\displaystyle\lim_{x \to +\infty}\left(1-\dfrac{3}{x}\right)^{2x}=e^{-6}.$

:::

